version: '3.3'

services:
  jira:
    image: luizcarlosfaria/jira:7.6.0
#    ports:
#      - "8081:8080"
    volumes:
      - ./data/:/var/atlassian/application-data/jira/
    networks:
      - front


networks:
  front:
    external: true