version: '3.3'

services:
  jira:
    image: luizcarlosfaria/jira:7.12.1
    ports:
      - "8081:8080"
    volumes:
      - jira_data:/var/atlassian/application-data/jira/
    networks:
      - LoadBalancer

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: jira
      MYSQL_USER: jirauser
      MYSQL_PASSWORD: jirapwd
    networks:
      - LoadBalancer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - LoadBalancer


volumes:
  jira_data:

networks:
  LoadBalancer:
    external: true